### ISSUE TITLE
More detailed information on installation

### ISSUE THREAD

**Issue by FaraoneLele** [keshavbhatt/snapcraft-gui#1]
please, write more in-depth information about the installation of this GUI, at present do not understand how to install it (I'm not an expert)

**Comment by keshavbhatt** [comment]
hi , i started this project on morning ,it is a concept , am implementing everything for now a user can -

- create a new snapcraft project

- open snapcraft project

- browse the project tree

- edit and save snapcraft.yaml with editor

- can see what snapcraft doing in background in output pan

am working on it , sure i will add installation methods when it will be not be :100: % but able to perform basic functionalities.

i will package debian .deb of this tool soon.
and put the installations instructions there .

for now you can grab the source from here open it with ubuntu sdk on 16.04 (my current ubuntu version and sdk setup ) compile it and run it on Ubuntu .
Thanks

**Comment by keshavbhatt** [comment]
Hi, the project can now be tested on Ubuntu 16.04 and above by adding daily build ppa to system. See the installation instructions in [readme.md](https://github.com/keshavbhatt/snapcraft-gui#install-on-ubuntu-1604-and-above)
