### ISSUE TITLE
Add a .snap file and a .deb file to your pre-release

### ISSUE THREAD

**Issue by tsimonq2** [keshavbhatt/snapcraft-gui#13]
This will ensure that it's easy to download and use.

Also, correct `apt-get` -> `apt`.

**Comment by keshavbhatt** [comment]
@tsimonq2 am not sure which .deb file i should put in there , as the tool is in development state. 
so ,i thought adding a hard coded link to an old .deb will be not good so i added the ppa information along with the  installation instructions.
 Will do this in future for sure though..
thanks

**Comment by tsimonq2** [comment]
@keshavbhatt take the .tar file and create a snap and a deb from that.

**Comment by keshavbhatt** [comment]
i have local build environment and having .deb of every version but i want users to use the latest version as it will feature new improvements and updates . :100:

**Comment by tsimonq2** [comment]
I see, then it's useless until the program is ready.
