### ISSUE TITLE
Typo error

### ISSUE THREAD

**Issue by FaraoneLele** [keshavbhatt/snapcraft-gui#22]
There is a typo error in about page
![image](https://cloud.githubusercontent.com/assets/17162630/18412754/0400c9cc-7797-11e6-8836-9f7394b19d1f.jpg)
Desgined should be Designed

**Comment by tsimonq2** [comment]
In addition, `opensource` should be `Open Source`, `repoting` should be `reporting`, and `comminting` should be `commenting`.

**Comment by keshavbhatt** [comment]
wow :P you got an eagle eye man :+1:  will fix them soon . Ty once again .
