### ISSUE TITLE
Add an icon

### ISSUE THREAD

**Issue by tsimonq2** [keshavbhatt/snapcraft-gui#23]
You should add an icon to this program, so users will be able to identify it by the icon.

**Comment by keshavbhatt** [comment]
icons come after you install the real package , from ppa or from .deb if you compiling source or building locally you wont get one :) though , i will add icon to binary by doing some hacks in my code . thanks for reminding me about this :package:

**Comment by keshavbhatt** [comment]
@tsimonq2 i fixed this real quick , plz close this if it working as expected..

**Comment by tsimonq2** [comment]
Works as intended, thanks! :)
